#pragma namespace ("root/cimv2")
#pragma include ("SUSE_SoftwareIdentity.mof")
#pragma include ("SUSE_InstalledSoftwareIdentity.mof")
#pragma include ("SUSE_SystemSpecificCollection.mof")
#pragma include ("SUSE_MemberOfCollection.mof")
#pragma include ("SUSE_HostedCollection.mof")
#pragma include ("SUSE_SoftwareInstallationService.mof")
#pragma include ("SUSE_InstallationServiceAffectsSoftwareIdentity.mof")

