//#pragma namespace ("root/cimv2")


// -------------------------------------------------------------------
// *******************************************************************
//      Classes
// *******************************************************************
// -------------------------------------------------------------------



// ===================================================================
//      SUSE_InstalledSoftwareIdentity
// ===================================================================

[ Provider("cmpi:cmpi-zypp"),
  Description ("Association between System and SoftwareIdentity")
]
class SUSE_InstalledSoftwareIdentity : CIM_InstalledSoftwareIdentity
{ 
      [Key, Description (
          "The system on which the software is installed." )]
   CIM_ComputerSystem REF System;

      [Override ( "InstalledSoftware" ),
       Description ( "The SoftwareIdentity that is installed." )]
   SUSE_SoftwareIdentity REF InstalledSoftware;
};


