//#pragma namespace ("root/cimv2")


// -------------------------------------------------------------------
// *******************************************************************
//      Classes
// *******************************************************************
// -------------------------------------------------------------------



// ===================================================================
//      SUSE_MemberOfCollection
// ===================================================================

[ Provider("cmpi:cmpi-zypp"),
  Description ("Association between SystemSpecificCollection and SoftwareIdentity")
]
class SUSE_MemberOfCollection : CIM_MemberOfCollection
{ };


