//#pragma namespace ("root/cimv2")


// -------------------------------------------------------------------
// *******************************************************************
//      Classes
// *******************************************************************
// -------------------------------------------------------------------



// ===================================================================
//      SUSE_InstalledSoftwareIdentity
// ===================================================================

[ Provider("cmpi:cmpi-zypp"),
  Description ("Association between System and SoftwareIdentity")
]
class SUSE_InstalledSoftwareIdentity : CIM_InstalledSoftwareIdentity
{ };


