//#pragma namespace ("root/cimv2")


// -------------------------------------------------------------------
// *******************************************************************
//      Classes
// *******************************************************************
// -------------------------------------------------------------------



// ===================================================================
//      SUSE_HostedInstallationService
// ===================================================================

[ Provider("cmpi:cmpi-zypp"),
  Description ("Association between System and SoftwareInstallationService")
]
class SUSE_HostedInstallationService : CIM_HostedService
{
      [Override ( "Antecedent" ),
       Min ( 1 ),
       Max ( 1 ),
       Description ( "The hosting system." )]
   CIM_ComputerSystem REF Antecedent;

      [Override ( "Dependent" ),
       Description (
          "The Service hosted on the System." )]
   SUSE_SoftwareInstallationService REF Dependent;
};


