//#pragma namespace ("root/cimv2")


// -------------------------------------------------------------------
// *******************************************************************
//      Classes
// *******************************************************************
// -------------------------------------------------------------------



// ===================================================================
//      SUSE_InstalledSoftwareIdentity
// ===================================================================

[ Provider("cmpi:cmpi-zypp"),
  Description ("A System Specific Collection representing Available Software.")
]
class SUSE_SystemSpecificCollection : CIM_SystemSpecificCollection
{ };


