//#pragma namespace ("root/cimv2")


// -------------------------------------------------------------------
// *******************************************************************
//      Classes
// *******************************************************************
// -------------------------------------------------------------------



// ===================================================================
//      SUSE_SoftwareIdentity
// ===================================================================

[ Provider("cmpi:cmpizypp"),
  Description ("A class derived from SoftwareIdentity"
  " to represent a resolvable software identity." )
]
class SUSE_SoftwareIdentity : CIM_SoftwareIdentity
{ };


