if(SBLIMCMPI_INCLUDE_DIR AND SBLIMCMPI_LIBRARY)
  # Already in cache, be silent
  set(SBLIMCMPI_FIND_QUIETLY TRUE)
endif(SBLIMCMPI_INCLUDE_DIR AND SBLIMCMPI_LIBRARY)

set(SBLIMCMPI_LIBRARY)
set(SBLIMCMPI_INCLUDE_DIR)

FIND_PATH(SBLIMCMPI_INCLUDE_DIR cmpi/CmpiInstanceMI.h
  /usr/include
  /usr/local/include
)

FIND_LIBRARY(SBLIMCMPI_LIBRARY NAMES cmpiCppImpl
  PATHS
  /usr/lib
  /usr/local/lib
)

if(SBLIMCMPI_INCLUDE_DIR AND SBLIMCMPI_LIBRARY)
  MESSAGE( STATUS "sblim-cmpi found: includes in ${SBLIMCMPI_INCLUDE_DIR}, library in ${SBLIMCMPI_LIBRARY}")
  set(SBLIMCMPI_FOUND TRUE)
else(SBLIMCMPI_INCLUDE_DIR AND SBLIMCMPI_LIBRARY)
  MESSAGE( STATUS "sblim-cmpi not found")
endif(SBLIMCMPI_INCLUDE_DIR AND SBLIMCMPI_LIBRARY)

MARK_AS_ADVANCED(SBLIMCMPI_INCLUDE_DIR SBLIMCMPI_LIBRARY)
