if(CMPIUTIL_INCLUDE_DIR AND CMPIUTIL_LIBRARY)
  # Already in cache, be silent
  set(CMPIUTIL_FIND_QUIETLY TRUE)
endif(CMPIUTIL_INCLUDE_DIR AND CMPIUTIL_LIBRARY)

set(CMPIUTIL_LIBRARY)
set(CMPIUTIL_INCLUDE_DIR)

FIND_PATH(CMPIUTIL_INCLUDE_DIR cmpiutil/base.h
  /usr/include
  /usr/local/include
)

FIND_LIBRARY(CMPIUTIL_LIBRARY NAMES sblim-cmpiutil
  PATHS
  /usr/lib
  /usr/local/lib
)

if(CMPIUTIL_INCLUDE_DIR AND CMPIUTIL_LIBRARY)
  MESSAGE( STATUS "sblim-cmpiutil found: includes in ${CMPIUTIL_INCLUDE_DIR}, library in ${CMPIUTIL_LIBRARY}")
  set(CMPIUTIL_FOUND TRUE)
else(CMPIUTIL_INCLUDE_DIR AND CMPIUTIL_LIBRARY)
  MESSAGE( STATUS "sblim-cmpiutil not found")
endif(CMPIUTIL_INCLUDE_DIR AND CMPIUTIL_LIBRARY)

MARK_AS_ADVANCED(CMPIUTIL_INCLUDE_DIR CMPIUTIL_LIBRARY)
